apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
  labels:
    app: wisecow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: wisecow-app:latest   # Replace with DockerHub image if pushing remotely
        ports:
        - containerPort: 3000
        # Optional: you can add resources or environment variables here

